CREATE TABLE IF NOT EXISTS Client(
    CNP VARCHAR(10) PRIMARY KEY NOT NULL,
    Nume VARCHAR(20) NOT NULL,
    Adresa VARCHAR(30) NOT NULL,
    'Numar de telefon' VARCHAR(12) NOT NULL,
    Parola VARCHAR(16) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONTURI(
    'Numar cont' VARCHAR(20) PRIMARY KEY NOT NULL,
    CNP VARCHAR(10) NOT NULL,
    Sold REAL,
    FOREIGN KEY(CNP) REFERENCES Client(CNP)
);

CREATE TABLE IF NOT EXISTS Tranzactii(
    ID VARCHAR(20) PRIMARY KEY NOT NULL,
    'Numar Cont' VARCHAR(20) NOT NULL,
    Sold REAL,
    Descriere VARCHAR(60),
    FOREIGN KEY('Numar Cont') REFERENCES CONTURI('Numar Cont')
);